extends:
  - "@sinonjs/eslint-config"

plugins:
  - "@sinonjs/no-prototype-methods"

rules:
  "@sinonjs/no-prototype-methods/no-prototype-methods": error
  "jsdoc/require-param-type": off
  "jsdoc/require-jsdoc": off
  "jsdoc/tag-lines": off
